import streamlit as st

from utils.loader import (
    forecast30,
    forecast90,
)

from utils.metrics import executive_metrics

from components.cards import (
    section_title,
    kpi_card,
)

from components.charts import (
    forecast_chart,
)


def forecast_page():

    metrics = executive_metrics()

    section_title(
        "Sales Forecast",
        "Prophet model predictions with confidence intervals",
    )

    c1, c2, c3 = st.columns(3)

    with c1:
        kpi_card(
            "Forecast Accuracy",
            f"{metrics['accuracy']:.2f}%",
            "Model Performance",
            "#22C55E",
            "🎯",
        )

    with c2:
        kpi_card(
            "30-Day Forecast",
            f"{int(metrics['sales30']):,}",
            "Predicted Units",
            "#3B82F6",
            "📅",
        )

    with c3:
        kpi_card(
            "90-Day Forecast",
            f"{int(metrics['sales90']):,}",
            "Predicted Units",
            "#F59E0B",
            "📈",
        )

    st.markdown("---")

    st.subheader("90-Day Sales Forecast")

    st.plotly_chart(
        forecast_chart(forecast90),
        use_container_width=True,
    )

    st.markdown("---")

    tab1, tab2 = st.tabs([
        "30-Day Forecast",
        "90-Day Forecast",
    ])

    with tab1:

        st.dataframe(
            forecast30,
            use_container_width=True,
            hide_index=True,
        )

    with tab2:

        st.dataframe(
            forecast90,
            use_container_width=True,
            hide_index=True,
        )

    st.markdown("---")

    st.info(
        "The shaded region in the forecast chart represents the 95% confidence interval generated by the Prophet forecasting model."
    )